// Auto-generated by scripts/generate-categories.ps1 - do not edit by hand.
// Run: powershell -ExecutionPolicy Bypass -File scripts/generate-categories.ps1

const CATEGORIES = [
  {
    id: "architecture",
    label: "Architecture",
    cover: "images/architecture/_LVA1506-Pano.jpg",
    photos: [
      { src: "images/architecture/_LVA1506-Pano.jpg", title: "LVA1506 Pano", date: "" },
      { src: "images/architecture/_LVA1520.jpg", date: "" },
      { src: "images/architecture/ATP_9268.jpg", date: "" },
      { src: "images/architecture/DSC_0191.jpg", date: "" },
      { src: "images/architecture/DSC_2735.jpg", date: "" },
      { src: "images/architecture/DSC_8597.jpg", date: "" },
      { src: "images/architecture/DSC_8628.jpg", date: "" },
      { src: "images/architecture/DSC_8635.jpg", date: "" },
      { src: "images/architecture/DSC_8641.jpg", date: "" },
      { src: "images/architecture/DSC00115-Pano.jpg", title: "DSC00115 Pano", date: "" },
      { src: "images/architecture/DSC00226.jpg", date: "" },
      { src: "images/architecture/DSC00236.jpg", date: "" },
      { src: "images/architecture/DSC00237.jpg", date: "" },
      { src: "images/architecture/DSC00273.jpg", date: "" },
      { src: "images/architecture/DSC00315.jpg", date: "" },
    ]
  },
  {
    id: "flight",
    label: "Flight",
    cover: "images/flight/CCBAS-114.jpg",
    photos: [
      { src: "images/flight/CCBAS-114.jpg", date: "" },
      { src: "images/flight/CCBAS-123.jpg", date: "" },
      { src: "images/flight/CCBAS-140.jpg", date: "" },
      { src: "images/flight/CCBAS-145.jpg", date: "" },
      { src: "images/flight/CCBAS-163.jpg", date: "" },
      { src: "images/flight/CCBAS-185.jpg", date: "" },
      { src: "images/flight/CCBAS-24.jpg", date: "" },
      { src: "images/flight/CCBAS-26.jpg", date: "" },
      { src: "images/flight/CCBAS-77.jpg", date: "" },
      { src: "images/flight/CCBAS-86.jpg", date: "" },
      { src: "images/flight/CCBAS-99.jpg", date: "" },
      { src: "images/flight/DSC_5430.jpg", date: "" },
      { src: "images/flight/DSC_5541.jpg", date: "" },
      { src: "images/flight/DSC_6065.jpg", date: "" },
      { src: "images/flight/DSC_6067-Enhanced-NR.jpg", title: "DSC 6067 Enhanced NR", date: "" },
    ]
  },
  {
    id: "landscapes",
    label: "Landscapes",
    cover: "images/landscapes/_LVA3512.jpg",
    photos: [
      { src: "images/landscapes/_LVA3512.jpg", date: "" },
      { src: "images/landscapes/_LVA3525-Pano.jpg", title: "LVA3525 Pano", date: "" },
      { src: "images/landscapes/_LVA3701.jpg", date: "" },
      { src: "images/landscapes/_LVA3841-HDR.jpg", title: "LVA3841 HDR", date: "" },
      { src: "images/landscapes/_LVA3961-HDR.jpg", title: "LVA3961 HDR", date: "" },
      { src: "images/landscapes/DSC_7207.jpg", date: "" },
      { src: "images/landscapes/DSC_8271-Pano.jpg", title: "DSC 8271 Pano", date: "" },
      { src: "images/landscapes/DSC_8640-Pano.jpg", title: "DSC 8640 Pano", date: "" },
      { src: "images/landscapes/DSC02348.jpg", date: "" },
    ]
  },
  {
    id: "portraits",
    label: "Portraits",
    cover: "images/portraits/DSC_4273.jpg",
    photos: [
      { src: "images/portraits/DSC_4273.jpg", date: "" },
      { src: "images/portraits/DSC_5710.jpg", date: "" },
      { src: "images/portraits/DSC_6020.jpg", date: "" },
      { src: "images/portraits/DSC_6882.jpg", date: "" },
      { src: "images/portraits/DSC_6886.jpg", date: "" },
      { src: "images/portraits/DSC_7377.jpg", date: "" },
      { src: "images/portraits/DSC_8536.jpg", date: "" },
      { src: "images/portraits/DSC_9038.jpg", date: "" },
      { src: "images/portraits/Wedding.jpg", title: "Wedding", date: "" },
    ]
  },
  {
    id: "rockets",
    label: "Rockets",
    cover: "images/rockets/B1067-35-4.jpg",
    photos: [
      { src: "images/rockets/B1067-35-4.jpg", title: "B1067 35 4", date: "" },
      { src: "images/rockets/CRS_NG-24_April 11, 2026-11.jpg", title: "CRS NG 24 April 11, 2026 11", date: "" },
      { src: "images/rockets/CRS_NG-24_April 11, 2026-2.jpg", title: "CRS NG 24 April 11, 2026 2", date: "" },
      { src: "images/rockets/CRS_NG-24_April 11, 2026-8.jpg", title: "CRS NG 24 April 11, 2026 8", date: "" },
      { src: "images/rockets/DSC_0957-20260411.jpg", title: "DSC 0957 20260411", date: "" },
      { src: "images/rockets/NewGlenn2_November 18, 2025-3.jpg", title: "NewGlenn2 November 18, 2025 3", date: "" },
      { src: "images/rockets/NewGlenn2_November 20, 2025.jpg", title: "NewGlenn2 November 20, 2025", date: "" },
      { src: "images/rockets/NewGlenn2-3.jpg", title: "NewGlenn2 3", date: "" },
      { src: "images/rockets/NG2_November 20, 2025.jpg", title: "NG2 November 20, 2025", date: "" },
    ]
  },
  {
    id: "streaks",
    label: "Streaks",
    cover: "images/streaks/AtlasV_ViaSat-3 F2_November 13, 2025.jpg",
    photos: [
      { src: "images/streaks/AtlasV_ViaSat-3 F2_November 13, 2025.jpg", title: "AtlasV ViaSat 3 F2 November 13, 2025", date: "" },
      { src: "images/streaks/AtlasV551_LA-06_April 27, 2026.jpg", title: "AtlasV551 LA 06 April 27, 2026", date: "" },
      { src: "images/streaks/B1076_SpainSatNGII_2_October 23, 2025.jpg", title: "B1076 SpainSatNGII 2 October 23, 2025", date: "" },
      { src: "images/streaks/B1080_Starlink 6-100_January 18, 2026.jpg", title: "B1080 Starlink 6 100 January 18, 2026", date: "" },
      { src: "images/streaks/B1085.12_Starlink 6-94_November 18, 2025.jpg", title: "B1085.12 Starlink 6 94 November 18, 2025", date: "" },
      { src: "images/streaks/B1085.12_Starlink 6-94_November 18, 2025-2.jpg", title: "B1085.12 Starlink 6 94 November 18, 2025 2", date: "" },
      { src: "images/streaks/B1091_Kuiper_KF-03-1_ October 13, 2025.jpg", title: "B1091 Kuiper KF 03 1 October 13, 2025", date: "" },
      { src: "images/streaks/B1094.5_Starlink 6-81_November 05, 2025.jpg", title: "B1094.5 Starlink 6 81 November 05, 2025", date: "" },
      { src: "images/streaks/B1094.5_Starlink 6-81_November 05, 2025-2.jpg", title: "B1094.5 Starlink 6 81 November 05, 2025 2", date: "" },
      { src: "images/streaks/B1101.2_Crew-12_2_February 13, 2026.jpg", title: "B1101.2 Crew 12 2 February 13, 2026", date: "" },
      { src: "images/streaks/B1101.2_Crew-12_February 13, 2026.jpg", title: "B1101.2 Crew 12 February 13, 2026", date: "" },
      { src: "images/streaks/Delta IV Heavy_NROL-44_December 10, 2020.JPG", title: "Delta IV Heavy NROL 44 December 10, 2020", date: "" },
      { src: "images/streaks/Starlink 10-38_B1077.26_February 19, 2026.jpg", title: "Starlink 10 38 B1077.26 February 19, 2026", date: "" },
      { src: "images/streaks/Starlink 10-41_ B1078.26_March 01, 2026.jpg", title: "Starlink 10 41 B1078.26 March 01, 2026", date: "" },
      { src: "images/streaks/Starlink 6-104_ B1067.33_February 21, 2026.jpg", title: "Starlink 6 104 B1067.33 February 21, 2026", date: "" },
      { src: "images/streaks/Starlink 6-11_ B1092.10_February 24, 2026.jpg", title: "Starlink 6 11 B1092.10 February 24, 2026", date: "" },
      { src: "images/streaks/Vulcan_USSF-106_August 12, 2025.jpg", title: "Vulcan USSF 106 August 12, 2025", date: "" },
    ]
  },
];

