// Auto-generated by scripts/generate-categories.ps1 - do not edit by hand.
// Run: powershell -ExecutionPolicy Bypass -File scripts/generate-categories.ps1

const CATEGORIES = [
  {
    id: "architecture",
    label: "Architecture",
    cover: "images/architecture/DSC00197.jpg",
    photos: [
      { src: "images/architecture/DSC00197.jpg", date: "" },
      { src: "images/architecture/DSC00226.jpg", date: "" },
      { src: "images/architecture/DSC00236.jpg", date: "" },
      { src: "images/architecture/DSC00237.jpg", date: "" },
      { src: "images/architecture/DSC00273.jpg", date: "" },
      { src: "images/architecture/DSC00315.jpg", date: "" },
    ]
  },
  {
    id: "flight",
    label: "Flight",
    cover: "images/flight/CCBAS-123.jpg",
    photos: [
      { src: "images/flight/CCBAS-123.jpg", date: "" },
      { src: "images/flight/CCBAS-185.jpg", date: "" },
      { src: "images/flight/CCBAS-77.jpg", date: "" },
      { src: "images/flight/CCBAS-99.jpg", date: "" },
      { src: "images/flight/DSC_6065.jpg", date: "" },
      { src: "images/flight/DSC_6067-Enhanced-NR.jpg", title: "DSC 6067 Enhanced NR", date: "" },
    ]
  },
  {
    id: "landscapes",
    label: "Landscapes",
    cover: "images/landscapes/_LVA3512.jpg",
    photos: [
      { src: "images/landscapes/_LVA3512.jpg", date: "" },
      { src: "images/landscapes/_LVA3841-HDR.jpg", title: "LVA3841 HDR", date: "" },
      { src: "images/landscapes/_LVA3961-HDR.jpg", title: "LVA3961 HDR", date: "" },
    ]
  },
  {
    id: "portraits",
    label: "Portraits",
    cover: "images/portraits/DSC_4273.jpg",
    photos: [
      { src: "images/portraits/DSC_4273.jpg", date: "" },
      { src: "images/portraits/DSC_6882.jpg", date: "" },
      { src: "images/portraits/DSC_7377.jpg", date: "" },
      { src: "images/portraits/Wedding.jpg", title: "Wedding", date: "" },
    ]
  },
];

