# Scans images/ subfolders and regenerates scripts/categories.js
# Run: powershell -ExecutionPolicy Bypass -File scripts/generate-categories.ps1

$projectRoot = Split-Path $PSScriptRoot -Parent
$imagesDir   = Join-Path $projectRoot "images"
$outputFile  = Join-Path $PSScriptRoot "categories.js"
$imageExts   = @('.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif')

function ConvertTo-Label([string]$name) {
    $words = ($name -replace '[-_]', ' ') -split ' '
    ($words | ForEach-Object { $_.Substring(0,1).ToUpper() + $_.Substring(1) }) -join ' '
}

function ConvertTo-Title([string]$filename) {
    $base = [System.IO.Path]::GetFileNameWithoutExtension($filename)
    # Camera-generated names like DSC00197, _LVA3512, IMG_4321 have no useful title
    if ($base -match '^[_-]?[A-Za-z]{2,5}[_-]?\d+$') { return '' }
    $words = ($base -replace '[-_]', ' ') -split ' ' | Where-Object { $_ -ne '' }
    if (-not $words) { return '' }
    return ($words | ForEach-Object { $_.Substring(0,1).ToUpper() + $_.Substring(1) }) -join ' '
}

if (-not (Test-Path $imagesDir)) {
    Write-Error "images/ folder not found at: $imagesDir"
    exit 1
}

$categoryFolders = Get-ChildItem $imagesDir -Directory | Sort-Object Name

if ($categoryFolders.Count -eq 0) {
    Write-Error "No category subfolders found inside images/"
    exit 1
}

$output = New-Object System.Collections.Generic.List[string]
$output.Add("// Auto-generated by scripts/generate-categories.ps1 - do not edit by hand.")
$output.Add("// Run: powershell -ExecutionPolicy Bypass -File scripts/generate-categories.ps1")
$output.Add("")
$output.Add("const CATEGORIES = [")

foreach ($folder in $categoryFolders) {
    $files = Get-ChildItem $folder.FullName -File |
        Where-Object { $imageExts -contains $_.Extension.ToLower() } |
        Sort-Object Name

    $coverFile = $files | Where-Object { $_.Name -match '^cover\.' } | Select-Object -First 1
    if (-not $coverFile) { $coverFile = $files | Select-Object -First 1 }
    $coverSrc = if ($coverFile) { "images/$($folder.Name)/$($coverFile.Name)" } else { '' }

    $photoFiles = $files | Where-Object { $_.Name -notmatch '^cover\.' }

    $label = ConvertTo-Label $folder.Name
    $output.Add("  {")
    $output.Add("    id: `"$($folder.Name)`",")
    $output.Add("    label: `"$label`",")
    $output.Add("    cover: `"$coverSrc`",")
    $output.Add("    photos: [")

    foreach ($f in $photoFiles) {
        $src   = "images/$($folder.Name)/$($f.Name)"
        $title = ConvertTo-Title $f.Name
        if ($title) {
            $output.Add("      { src: `"$src`", title: `"$title`", date: `"`" },")
        } else {
            $output.Add("      { src: `"$src`", date: `"`" },")
        }
    }

    $output.Add("    ]")
    $output.Add("  },")
}

$output.Add("];")
$output.Add("")

# Write UTF-8 without BOM so browsers load it cleanly
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllLines($outputFile, $output, $utf8NoBom)

Write-Host ""
Write-Host "Wrote $outputFile"
Write-Host ""

foreach ($folder in $categoryFolders) {
    $files = Get-ChildItem $folder.FullName -File |
        Where-Object { $imageExts -contains $_.Extension.ToLower() }
    $photoCount = ($files | Where-Object { $_.Name -notmatch '^cover\.' }).Count
    $coverFile  = ($files | Where-Object { $_.Name -match '^cover\.' } | Select-Object -First 1)
    if (-not $coverFile) { $coverFile = $files | Select-Object -First 1 }
    $coverName  = if ($coverFile) { $coverFile.Name } else { 'none' }
    Write-Host "  $($folder.Name): $photoCount photos, cover: $coverName"
}

Write-Host ""
